name: Fetch Jobs Every 6 Hours

on:
  schedule:
    # Run every 6 hours (00:00, 06:00, 12:00, 18:00 UTC)
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  fetch-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create .env.local
        run: |
          cat > .env.local << EOF
          # MongoDB Atlas Configuration
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          MONGODB_DB_NAME=job-board
          MONGODB_COLLECTION=jobs

          # RapidAPI Configuration
          RAPIDAPI_KEY=${{ secrets.RAPIDAPI_KEY }}

          # Admin Configuration
          NEXT_PUBLIC_ADMIN_PASSWORD=admin123

          # LinkedIn Social Media Configuration
          LINKEDIN_ACCESS_TOKEN=${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          LINKEDIN_ORGANIZATION_ID=${{ secrets.LINKEDIN_ORGANIZATION_ID }}
          EOF

      - name: Fetch and add jobs
        run: npm run scrape

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/jobs.json
          git commit -m "🤖 Auto-update: Added new jobs from RapidAPI" || echo "No changes to commit"
          git push
