name: Scrape Jobs

on:
  schedule:
    # Run every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Add timeout to prevent hanging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci
        timeout-minutes: 5

      - name: Install dotenv
        run: npm install dotenv
        timeout-minutes: 2

      - name: Set up environment variables
        run: |
          echo "RAPIDAPI_KEY=${{ secrets.RAPIDAPI_KEY }}" >> $GITHUB_ENV
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV
          echo "MONGODB_DB_NAME=${{ secrets.MONGODB_DB_NAME }}" >> $GITHUB_ENV
          echo "MONGODB_COLLECTION=${{ secrets.MONGODB_COLLECTION }}" >> $GITHUB_ENV
        timeout-minutes: 1

      - name: Run scraper
        run: npm run scrape
        timeout-minutes: 8

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
        timeout-minutes: 1

      - name: Commit and push changes
        run: |
          git add data/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update job listings [skip ci]"
            git push
          fi
        timeout-minutes: 3
